name: benchmark

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build
        run: |
          docker buildx build -t sovrin-metadata:cli --output "type=docker,push=false,name=sovrin-metadata:cli" .

      - name: Run benchmark on live
        run: |
          docker run -i sovrin-metadata:cli < benchmark_queries.txt

      - name: Run benchmark on builder
        run: |
          docker run -i sovrin-metadata:cli --ledger builder < benchmark_queries.txt

      - name: Run benchmark on sandbox
        run: |
          echo "first name" | docker run -i sovrin-metadata:cli --ledger sandbox
